---
apiVersion: v1
kind: Namespace
metadata:
  name: dapr-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dapr
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://dapr.github.io/helm-charts/'
      chart: dapr
      targetRevision: 1.9.6
    - repoURL: 'https://github.com/roeilevinson/monkey-manifests'
      targetRevision: HEAD
      path: dapr/ingress
      directory:
        recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dapr-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: false


