---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-events
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/argoproj/argo-helm'
    path:  charts/argo-events
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-events
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
