apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monkey-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/roeilevinson/monkey-react-helm'
    path: .
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
