apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monkey-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/roeilevinson/monkey-react-helm'
      path: .
      targetRevision: HEAD
    # - repoURL: 'https://github.com/roeilevinson/monkey-manifests'
    #   targetRevision: HEAD
    #   path: app/ingress
      # directory:
      #   recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
