apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
    project: default
    sources:
      - repoURL: 'https://github.com/argoproj/argo-helm'
        path: charts/argo-cd
        targetRevision: HEAD
      - repoURL: 'https://github.com/roeilevinson/monkey-manifests'
        targetRevision: HEAD
        path: argocd/ingress
        directory:
          recurse: true
    destination:
      server: 'https://kubernetes.default.svc'
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

# helm: 
#       parameters:
#         - name: server.service.type
#           value: LoadBalancer