---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami/'
      chart:  kafka
      targetRevision: 21.4.0
      helm:
        values: |
          provisioning:
            enabled: true
            topics:
              - name: topic1
                partitions: 1
                replicationFactor: 1
              - name: topic2
                partitions: 3
                replicationFactor: 1
              - name: topic3
                partitions: 2
                replicationFactor: 2
          replicaCount: 3 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: false


